name: Publish Docker image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Run mapping generator
        run: go run cmd/mappinggenerator/*.go

      - name: Build config generator
        run: go build -o docker-build/ocbconfigbuilder cmd/configgenerator/*.go

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ github.repository }}:nightly
          push: true
